### ISSUE TITLE
l want to know how to use this , npm start isn't useful 

### ISSUE THREAD

**Issue by Ai01** [AKolodeev/connect6-client#1]
thankyou

**Comment by AKolodeev** [comment]
Hi, @Ai01! Unfortunately, this project isn't ready yet. You need to add `index.html` and add `<script src=bundle.js" manually. I will fix it later.

**Comment by AKolodeev** [comment]
Hi, @Ai01. I have fixed this issue. So you can try it now if you still need :)
You also need my connect6-server for the game.

**Comment by Ai01** [comment]
thank you very much.
l already start the program.but l can't play with your wonderful job,it just has a board.
anyway thank you again. @AKolodeev
